vich_uploader:
    db_driver: orm

    mappings:
        thumbnails:
            uri_prefix: '%env(VICH_URI_PREFIX)%'
            upload_destination: '%kernel.project_dir%.%env(VICH_UPLOAD_DESTINATION)%'
